on:
  push:
    tags:
      - v*.*.*

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: pnpm/action-setup@v6.0.8
        with:
          version: latest

      - uses: actions/setup-node@v6.4.0
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org/"

      - name: Set version
        run: pnpm version ${{ github.ref_name }} --no-git-tag-version

      - name: Publish
        run: pnpm publish --access public --no-git-checks
